/*
 * config.h
 *
 *  Created on: 8. 10. 2020
 *      Author: petr.horacek
 */

#ifndef INCLUDE_CONFIG_H_
#define INCLUDE_CONFIG_H_


#include "glass_info.h"

#define IP_ADDRESS "192.168.2.1"
#define RACK 0
#define SLOT 1
#define DB_INDEX 1//5

#define QUEUE_FILE_PATH "queue.dat"




#define VEHICLE_NUMBER_LENGTH 13
#define REAR_WINDOW_TYPE_LENGTH 20
#define CALLOFF_DATE_TIME_LENGTH 16
#define JOB_NUMBER_LENGTH 10
#define PRODUCTION_SEQ_LENGTH 6
#define VEHICLE_MODE_LENGTH 1
#define ID_LENGTH 4


#define JOB_NUMBER_BYTE_INDEX 0
#define CALLOFF_DATE_TIME_BYTE_INDEX (JOB_NUMBER_BYTE_INDEX + JOB_NUMBER_LENGTH)
#define VEHICLE_NUMBER_BYTE_INDEX (CALLOFF_DATE_TIME_BYTE_INDEX + CALLOFF_DATE_TIME_LENGTH)
#define REAR_WINDOW_TYPE_BYTE_INDEX (VEHICLE_NUMBER_BYTE_INDEX + VEHICLE_NUMBER_LENGTH+1)
#define VEHICLE_MODEL_BYTE_INDEX (REAR_WINDOW_TYPE_BYTE_INDEX + REAR_WINDOW_TYPE_LENGTH)
#define ID_BYTE_INDEX (VEHICLE_MODEL_BYTE_INDEX + VEHICLE_MODE_LENGTH+1)
#define PRODUCTION_SEQ_BYTE_INDEX (ID_BYTE_INDEX + ID_LENGTH)




#define CMD_BYTE 72
#define STATUS_BYTE 796

#define GLASS_BYTE 0
#define GLASS_SIZE sizeof(glass_info)

#define CMD_ENQUEUE_BYTE CMD_BYTE
#define CMD_ENQUEUE_BIT 0

#define CMD_PRIORITY_ENQUEUE_BYTE CMD_BYTE
#define CMD_PRIORITY_ENQUEUE_BIT 1

#define CMD_DEQUEUE_BYTE CMD_BYTE
#define CMD_DEQUEUE_BIT 2

#define CMD_CLEAN_QUEUE_BYTE CMD_BYTE
#define CMD_CLEAN_QUEUE_BIT 3

#define CMD_RELOAD_VISU_BYTE CMD_BYTE
#define CMD_RELOAD_VISU_BIT 4

#define VISU_BYTE 74
#define VISU_ITEM_NUMBERN 10
#define VISU_SIZE GLASS_SIZE*VISU_ITEM_NUMBERN

#define VISU_QUEUE_SIZE_BYTE VISU_BYTE+VISU_SIZE

#define DONE_BYTE STATUS_BYTE
#define DONE_BIT 0

#define ERROR_BYTE STATUS_BYTE
#define ERROR_BIT 1

#define LIVE_FLAG_BYTE STATUS_BYTE
#define LIVE_FLAG_BIT 2




#endif /* INCLUDE_CONFIG_H_ */
